apiVersion: v1
kind: Secret
metadata:
  name: healthlink-backend-secret
  namespace: healthlink-namespace
type: Opaque
data:
  JWT_KEY: aGVhbHRobGluay1tb3JhLWRldl9zZWNyZXQ=   # Base64 encoded
  DB_PASSWORD: QVZOU191MFZCMk01M3didjhYNnlfY3F4   # Base64 encoded
